language: scala
jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.13.1
before_script:
  - script/bootstrap
script:
  - script/cibuild
notifications:
  email:
    recipients:
      - travis@kevinvandervlist.nl
    on_success: never # default: change
    on_failure: always # default: always
